title: Mind the Gaps
description: |
  Mind the Gaps is an **open toolbox** to measure and produce data around  wellbeing and inequalities in cities.

  We designed a variety of methods to collect this information — ethnographic interview guides, a conversational survey.

  Its aim is to fill the gaps in statistics by using **human centred methods** of information collection.
footer_description: |
  We are an **independant data collective** of researchers, artists, developers and ethnographers.
  We are based in France 🇫🇷, London 🇬🇧 and Montréal 🇨🇦.

  The project is backed by the non-profit cooperative
  [dtc innovation](https://dtc-innovation.org).
  We do not track nor collect any personal data.
  And will never do, not even for money.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mind-the-gaps.org"
lang: en_GB
twitter_username:
github_username:
email: "&#x68;&#x65;&#x6c;&#x6c;&#x6f;&#x40;&#x6d;&#x69;&#x6e;&#x64;&#x2d;&#x74;&#x68;&#x65;&#x2d;&#x67;&#x61;&#x70;&#x73;&#x2e;&#x6f;&#x72;&#x67;"
github_project: https://github.com/dtc-innovation/mind-the-gaps/
newsletter: https://tinyletter.com/mind-the-gaps
slackin: https://slack.dtc-innovation.org
slack_channel: projet-mind-the-gaps

flags:
  France: 🇫🇷
  UK: 🇬🇧

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-money

timezone: Europe/London
milestones:
  work_week_start: 2018-01-14T00:00:00
  work_week_end: 2018-01-19T20:00:00

header_pages:
  # - fr/index.html
  - about.md
  - research/index.md

research_header_pages:
  - research/toolbox.md
  - research/glossary.md
  - research/about.md

collections:
  contexts:
    output: true
    permalink: /for/:name
  features:
    output: false

defaults:
  - scope:
      path: "research"
      type: "pages"
    values:
      layout: page-research

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
