title: Mind the Gaps
email: mind-the-gaps@framalistes.org
description: >- # this means to ignore newlines until "baseurl:"
  An encouraging map aimed at highlighting city inequalities and possible pathways to their resolutions.
baseurl: "/mind-the-gaps" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
