title: Mind the Gaps
email: mind-the-gaps@framalistes.org
description: |
  Mind the Gaps is a thought provoking **experiment** to bring citizen sensing closer to policy making. It is a **system** for open data collection about well-being and inequalities in cities.

  It will invite citizens to **paint a more comprehensive picture** of their experience of their neighbourhood.

  It adds qualitative and granular data to existing robust datasets.
  This will aim to stimulate open discussions and help policy makers build more resilient cities.
baseurl: "/mind-the-gaps" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en_GB
twitter_username:
github_username:
github_project: https://github.com/dtc-innovation/mind-the-gaps/
newsletter: https://tinyletter.com/mind-the-gaps

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

timezone: Europe/London
work_week1_date: 2018-01-14T00:00:00
recent_posts_since: 2018-01-27T00:00:00

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
