name: Jekyll site CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: meitar/jekyll-builder-for-github-pages@v1
